import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const url = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY!;
if (!url || !key) { process.exit(1); }

const sb = createClient(url, key, { auth: { autoRefreshToken: false, persistSession: false } });

const grants: any[] = [
  {
    slug: 'eu-strengthening-civil-society-ethiopia',
    title: 'EU Action Grants: Strengthening Civil Society in Ethiopia',
    funding_org: 'European Commission',
    opportunity_id: 'EuropeAid/182336/DD/ACT/ET',
    teaser: 'Enhance the capacity of Ethiopian CSOs to participate in policy dialogue, monitor national development plans, and promote human rights and democratic governance at the local level.',
    full_description: 'This call aims to strengthen the role of Ethiopian civil society in governance processes. It supports CSOs in building institutional capacity, engaging in evidence-based policy dialogue, and monitoring the implementation of national development plans. The grant emphasizes human rights, democratic governance, and citizen participation at the local level. Total pool: €5,829,000.',
    target_audience: 'Local Civil Society Organizations (CSOs) in Ethiopia',
    min_amount: 250000, max_amount: 1000000, currency: 'EUR',
    funding_rate: 'Up to 90% (10% co-financing required)',
    funding_type: 'Grant', co_financing_required: true,
    deadline: '2026-05-13T15:30:00+02:00', deadline_timezone: 'Europe/Brussels',
    deadline_display_text: 'May 13, 2026 (15:30 Brussels Time / 16:30 EAT)',
    location: 'Ethiopia', sector: 'Civil Society & Governance',
    implementation_area: 'Ethiopia', category: 'Governance',
    countries: ['Ethiopia'], regions: ['East Africa'],
    tags: ['CSO', 'governance', 'human-rights', 'policy-dialogue'],
    application_link: 'https://ec.europa.eu/info/funding-tenders',
    application_platform: 'EU Funding & Tenders',
    eligibility_summary: 'Must be a non-profit legal entity established in Ethiopia, registered in PADOR.',
    eligibility_checklist: [{ item: 'Must be a non-profit legal entity (NGO/CSO)' }, { item: 'Must be established in Ethiopia' }, { item: 'Must be registered in PADOR and submit via PROSPECT' }],
    status: 'active', priority: 'high', is_featured: true, notify_me_enabled: true,
    published_at: '2026-04-01T00:00:00Z',
    duration_months: null,
    archived_reason: null
  },
  {
    slug: 'unicef-venture-fund-climate',
    title: 'UNICEF Venture Fund: Climate Ventures Cohort',
    funding_org: 'UNICEF',
    opportunity_id: 'UVF-2026-CLIM',
    teaser: 'Equity-free seed funding up to $100,000 for open-source frontier technology solutions addressing climate change impact on children and vulnerable communities.',
    full_description: 'The UNICEF Venture Fund invests in open-source, frontier technology solutions (AI, IoT, Blockchain) that address climate change\'s impact on children and vulnerable communities, particularly in WASH and agriculture. Includes technical mentorship and access to UNICEF\'s global network.',
    target_audience: 'Ag-tech and Climate-tech startups with a working prototype',
    min_amount: 50000, max_amount: 100000, currency: 'USD',
    funding_rate: '100%', funding_type: 'Seed Funding', co_financing_required: false,
    deadline: '2026-05-17T23:59:00+03:00', deadline_timezone: 'Africa/Addis_Ababa',
    deadline_display_text: 'May 17, 2026 (23:59 EAT)',
    location: 'Global (Includes Ethiopia, Kenya, Uganda)', sector: 'Technology & Innovation',
    implementation_area: 'Global', category: 'Innovation',
    countries: ['Ethiopia', 'Kenya', 'Uganda'], regions: ['East Africa', 'Global'],
    tags: ['climate-tech', 'AI', 'IoT', 'open-source', 'startups'],
    application_link: 'https://www.unicef.org/innovation/venturefund',
    application_platform: 'UNICEF Innovation Portal',
    eligibility_summary: 'For-profit private company in a UNICEF country with an open-source prototype.',
    eligibility_checklist: [{ item: 'Must be a for-profit private company registered in a UNICEF country' }, { item: 'Must have an existing open-source prototype' }, { item: 'Solution must benefit children and youth' }],
    status: 'active', priority: 'normal', is_featured: true, notify_me_enabled: true,
    published_at: '2026-04-10T00:00:00Z',
    duration_months: null,
    archived_reason: null
  },
  {
    slug: 'mit-solve-global-challenge-2026',
    title: 'MIT Solve: 10th Anniversary Global Challenge',
    funding_org: 'MIT Solve',
    opportunity_id: 'SOLVE-2026',
    teaser: 'Over $1,000,000 in prize funding for tech-based solutions across Climate Resilience, Health Equity, Learning Futures, and Economic Prosperity.',
    full_description: 'MIT Solve seeks tech-based solutions for four pillars: Climate Resilience, Health Equity, Learning Futures, and Economic Prosperity. Winners receive minimum $100,000 in unrestricted funding plus access to the Solve Community for follow-on capital and mentorship.',
    target_audience: 'Social entrepreneurs and tech-based innovators',
    min_amount: 100000, max_amount: 1000000, currency: 'USD',
    funding_rate: '100%', funding_type: 'Prize', co_financing_required: false,
    deadline: '2026-05-21T12:00:00-04:00', deadline_timezone: 'America/New_York',
    deadline_display_text: 'May 21, 2026 (12:00 PM EDT / 19:00 EAT)',
    location: 'Global (East Africa priority)', sector: 'Technology & Innovation',
    implementation_area: 'Global', category: 'Global Impact',
    countries: ['Global'], regions: ['Global'],
    tags: ['climate', 'health', 'education', 'economic-prosperity'],
    application_link: 'https://solve.mit.edu',
    application_platform: 'MIT Solve Portal',
    eligibility_summary: 'For-profit, non-profit, or hybrid using technology as core component.',
    eligibility_checklist: [{ item: 'Can be for-profit, non-profit, or hybrid' }, { item: 'Must use technology as a core component' }, { item: 'Must be available for Solve at MIT event in late 2026' }],
    status: 'active', priority: 'normal', is_featured: false, notify_me_enabled: true,
    published_at: '2026-04-05T00:00:00Z',
    duration_months: null,
    archived_reason: null
  },
  {
    slug: 'la-caixa-child-survival-2026',
    title: 'La Caixa Foundation: Child Survival Call',
    funding_org: '"la Caixa" Foundation',
    opportunity_id: 'LCF-CS-2026',
    teaser: '€150,000–€450,000 for consortiums addressing child mortality from pneumonia, malaria, diarrhea, and malnutrition in Sub-Saharan Africa.',
    full_description: 'Improving survival rates for children under five by addressing leading causes of mortality. Projects of 24 to 36 months with direct costs for health interventions in high-burden areas. Requires consortium of 3-5 registered non-profit entities with local partner.',
    target_audience: 'Partnerships between international foundations and local Ethiopian NGOs',
    min_amount: 150000, max_amount: 450000, currency: 'EUR',
    funding_rate: '100%', funding_type: 'Grant', co_financing_required: false,
    duration_months: 36,
    deadline: '2026-05-26T18:00:00+03:00', deadline_timezone: 'Africa/Addis_Ababa',
    deadline_display_text: 'May 26, 2026 (18:00 EAT)',
    location: 'Sub-Saharan Africa (Ethiopia Priority)', sector: 'Health & WASH',
    implementation_area: 'Sub-Saharan Africa', category: 'Health',
    countries: ['Ethiopia'], regions: ['East Africa', 'Southern Africa'],
    tags: ['child-health', 'malnutrition', 'consortium'],
    application_link: 'https://fundacionlacaixa.org',
    application_platform: 'La Caixa Hub',
    eligibility_summary: 'Network of 3-5 non-profit entities with local partner in implementation country.',
    eligibility_checklist: [{ item: 'Must be a network of 3–5 registered non-profit entities' }, { item: 'Must include at least one local partner in Ethiopia' }, { item: 'Proven experience in public health' }],
    status: 'active', priority: 'normal', is_featured: false, notify_me_enabled: true,
    published_at: '2026-04-15T00:00:00Z',
    archived_reason: null
  },
  {
    slug: 'giz-transformative-company-support',
    title: 'GIZ Transformative Company Support Programme',
    funding_org: 'GIZ (German Development Cooperation)',
    opportunity_id: 'GIZ-ETH-2026-TCS',
    teaser: 'High-value non-financial technical assistance for Ethiopian companies transitioning to Circular Economy — sustainable packaging, industrial recycling, resource efficiency.',
    full_description: 'Transitioning Ethiopian industries to a Circular Economy. Provides specialized consulting, equipment auditing, and industrial training. Companies must commit personnel and time. Focus on sustainable packaging, industrial recycling, and resource efficiency.',
    target_audience: 'Established Ethiopian companies in manufacturing or recycling',
    min_amount: null, max_amount: null, currency: 'USD',
    funding_rate: 'Non-financial (Technical Assistance)', funding_type: 'Technical Assistance', co_financing_required: false,
    deadline: '2026-05-22T23:59:00+03:00', deadline_timezone: 'Africa/Addis_Ababa',
    deadline_display_text: 'May 22, 2026 (23:59 EAT)',
    location: 'Ethiopia', sector: 'Private Sector & Industry',
    implementation_area: 'Ethiopia', category: 'Private Sector',
    countries: ['Ethiopia'], regions: ['East Africa'],
    tags: ['circular-economy', 'manufacturing', 'recycling'],
    application_link: 'https://2merkato.com',
    application_platform: 'GIZ Tenders / 2merkato',
    eligibility_summary: 'Private company in Ethiopia with 3+ years of operation.',
    eligibility_checklist: [{ item: 'Private company registered and operating in Ethiopia' }, { item: 'Minimum 3 years of active operation' }, { item: 'Must demonstrate potential for job creation and environmental impact' }],
    status: 'active', priority: 'normal', is_featured: false, notify_me_enabled: true,
    published_at: '2026-04-20T00:00:00Z',
    duration_months: null,
    archived_reason: null
  },
  {
    slug: 'code-for-africa-ai-fellowship-2026',
    title: 'Code for Africa: AI For Good Fellowship 2026',
    funding_org: 'Code for Africa (CfA)',
    opportunity_id: 'CFA-AI-2026',
    teaser: '$500/month stipend + tools for a 4-month remote fellowship using AI to solve public interest challenges — disinformation monitoring, environmental crime tracking, healthcare accessibility.',
    full_description: 'Using Artificial Intelligence to solve public interest challenges such as monitoring disinformation, tracking environmental crimes, or improving healthcare accessibility. Includes access to CfA data engineering and AI labs. 4-month remote fellowship.',
    target_audience: 'Individual technologists or small data teams',
    min_amount: 2000, max_amount: 2000, currency: 'USD',
    funding_rate: '$500/month', funding_type: 'Fellowship', co_financing_required: false,
    duration_months: 4,
    deadline: '2026-05-11T23:59:00+03:00', deadline_timezone: 'Africa/Addis_Ababa',
    deadline_display_text: 'May 11, 2026 (23:59 EAT)',
    location: 'Ethiopia, Kenya, and others', sector: 'AI & Data Science',
    implementation_area: 'East Africa', category: 'Digital Justice',
    countries: ['Ethiopia', 'Kenya'], regions: ['East Africa'],
    tags: ['AI', 'data-science', 'fellowship', 'disinformation'],
    application_link: 'https://codeforafrica.org/careers',
    application_platform: 'CfA Careers',
    eligibility_summary: 'Technologists, data scientists, or investigative researchers based in participating African countries.',
    eligibility_checklist: [{ item: 'Open to technologists, data scientists, and investigative researchers' }, { item: 'Must be based in a participating African country' }, { item: 'Must dedicate significant hours to fellowship projects' }],
    status: 'urgent', priority: 'high', is_featured: true, notify_me_enabled: true,
    published_at: '2026-04-01T00:00:00Z',
    archived_reason: null
  },
  {
    slug: 'eu-agri-nutrition-investments',
    title: 'EU Action Grants: Climate-Resilient Nutrition-Sensitive Agri-Food Investments',
    funding_org: 'European Commission',
    opportunity_id: 'EuropeAid/2026/ACT-AF-ET',
    teaser: '€4,000,000 pool for mobilizing sustainable investment into agri-food value chains to improve access to healthy diets for the poorest income quintiles.',
    full_description: 'Mobilizing sustainable investment into agri-food value chains to improve access to healthy diets for the poorest income quintiles, with a focus on minimally processed nutrient-rich foods. Must demonstrate private capital mobilization. Up to 90% of eligible costs funded.',
    target_audience: 'NGOs and investment-ready agri-businesses',
    min_amount: 200000, max_amount: 4000000, currency: 'EUR',
    funding_rate: 'Up to 90%', funding_type: 'Grant', co_financing_required: true,
    deadline: '2026-04-28T12:00:00+02:00', deadline_timezone: 'Europe/Brussels',
    deadline_display_text: 'April 28, 2026 (12:00 Brussels Time)',
    location: 'Ethiopia', sector: 'Agriculture & Nutrition',
    implementation_area: 'Ethiopia', category: 'Agri-Nutrition',
    countries: ['Ethiopia'], regions: ['East Africa'],
    tags: ['agri-food', 'nutrition', 'gender-transformative'],
    application_link: null,
    external_application_url: 'https://ec.europa.eu/info/funding-tenders',
    application_platform: 'EU Funding & Tenders',
    eligibility_summary: 'Non-profit legal entity with gender-transformative objectives.',
    eligibility_checklist: [{ item: 'Non-profit legal entity' }, { item: 'Must include measurable gender-transformative outcomes' }, { item: 'Sector focus: horticulture, animal-sourced foods, or fruits/vegetables' }],
    status: 'closed', priority: 'normal', is_featured: false, notify_me_enabled: true,
    archived_reason: 'Deadline passed April 28, 2026',
    published_at: '2026-03-15T00:00:00Z',
    duration_months: null
  },
  {
    slug: 'wfp-school-feeding-ethiopia',
    title: 'WFP Climate-Adaptive Livelihoods & School Feeding Programme',
    funding_org: 'World Food Programme (WFP)',
    opportunity_id: 'WFP-ETH-2026-05',
    teaser: 'Operational partnership integrating Home-Grown School Feeding with climate-resilient agriculture — sourcing school meals from local smallholders.',
    full_description: 'Integrating Home-Grown School Feeding with climate-resilient agriculture. The goal is to source school meals from local smallholders to boost both child nutrition and farmer income. Service-delivery based operational partnership.',
    target_audience: 'Local Ethiopian organizations with strong field presence',
    min_amount: null, max_amount: null, currency: 'USD',
    funding_rate: 'Variable', funding_type: 'Operational Partnership', co_financing_required: false,
    deadline: '2026-04-30T17:00:00+03:00', deadline_timezone: 'Africa/Addis_Ababa',
    deadline_display_text: 'April 30, 2026 (17:00 EAT)',
    location: 'Ethiopia (Specific Regional Focus)', sector: 'Emergency & Resilience',
    implementation_area: 'Ethiopia', category: 'Emergency Resilience',
    countries: ['Ethiopia'], regions: ['East Africa'],
    tags: ['school-feeding', 'climate-resilience', 'smallholders'],
    application_link: null,
    external_application_url: 'https://www.unpartnerportal.org',
    application_platform: 'UN Partner Portal',
    eligibility_summary: 'Local Ethiopian organizations with multi-sectoral project experience.',
    eligibility_checklist: [{ item: 'Priority given to local Ethiopian organizations' }, { item: 'Proven experience in integrated multi-sectoral projects' }, { item: 'Must be registered on the UN Partner Portal' }],
    status: 'archived', priority: 'normal', is_featured: false, notify_me_enabled: true,
    archived_reason: 'Deadline passed April 30, 2026',
    published_at: '2026-03-20T00:00:00Z',
    duration_months: null
  },
  {
    slug: 'icgeb-biotech-research-grant',
    title: 'ICGEB BiotechNet Collaborative Research Grant',
    funding_org: 'International Centre for Genetic Engineering and Biotechnology',
    opportunity_id: 'CRP-ETH-2026',
    teaser: '€25,000/year (max 36 months, €75,000 total) for original scientific research in life sciences, health services, and industrial/agricultural biotechnology.',
    full_description: 'Funding Original Scientific Problems of regional interest. Focus areas include basic life sciences, health services, and industrial/agricultural biotechnology. Competitive preference for Young Scientists under 40.',
    target_audience: 'University researchers and scientific institutes',
    min_amount: 25000, max_amount: 75000, currency: 'EUR',
    funding_rate: '100%', funding_type: 'Research Grant', co_financing_required: false,
    duration_months: 36,
    deadline: '2026-04-30T23:59:00+01:00', deadline_timezone: 'Europe/Berlin',
    deadline_display_text: 'April 30, 2026 (23:59 CET)',
    location: 'Ethiopia, Djibouti, Kenya, Uganda', sector: 'Education & Research',
    implementation_area: 'East Africa', category: 'Biotech Research',
    countries: ['Ethiopia', 'Djibouti', 'Kenya', 'Uganda'], regions: ['East Africa'],
    tags: ['biotech', 'research', 'young-scientists', 'life-sciences'],
    application_link: null,
    external_application_url: 'https://www.icgeb.org',
    application_platform: 'ICGEB Gateway',
    eligibility_summary: 'Principal Investigators at universities/research institutes with national Liaison Officer endorsement.',
    eligibility_checklist: [{ item: 'Principal Investigators at universities or research institutes' }, { item: 'Requires official endorsement from national Liaison Officer' }, { item: 'Competitive preference for Young Scientists under 40' }],
    status: 'closed', priority: 'normal', is_featured: false, notify_me_enabled: true,
    archived_reason: 'Deadline passed April 30, 2026',
    published_at: '2026-03-01T00:00:00Z'
  },
  {
    slug: 'wphf-womens-rights-ethiopia',
    title: "Women's Peace & Humanitarian Fund (WPHF) - Ethiopia",
    funding_org: 'UN Women / WPHF',
    opportunity_id: 'WPHF-ETH-2026',
    teaser: '$30,000–$200,000 for women-led CSOs supporting women\'s participation in humanitarian response and protection in conflict-affected settings.',
    full_description: "Supporting women's participation in humanitarian response and the protection of women and girls in conflict-affected settings. Programmatic grants ($30,000–$200,000) for project delivery plus institutional grants ($2,500–$30,000) for core organizational support.",
    target_audience: 'Women-led CSOs and community groups',
    min_amount: 30000, max_amount: 200000, currency: 'USD',
    funding_rate: '100%', funding_type: 'Grant', co_financing_required: false,
    deadline: '2026-04-21T23:59:00+03:00', deadline_timezone: 'Africa/Addis_Ababa',
    deadline_display_text: 'April 21, 2026',
    location: 'Ethiopia (Conflict-affected regions)', sector: 'Human Rights & Gender',
    implementation_area: 'Ethiopia', category: "Women's Rights",
    countries: ['Ethiopia'], regions: ['East Africa'],
    tags: ['womens-rights', 'humanitarian', 'gender', 'peacebuilding'],
    application_link: null,
    external_application_url: 'https://wphfund.org',
    application_platform: 'WPHF Portal',
    eligibility_summary: 'Women-led or women\'s rights organizations locally based in Ethiopia.',
    eligibility_checklist: [{ item: "Must be a women-led or women's rights organization" }, { item: 'Locally based CSOs in Ethiopia' }, { item: "Must align with UN Women's Peace and Security agenda" }],
    status: 'closed', priority: 'normal', is_featured: false, notify_me_enabled: true,
    archived_reason: 'Deadline passed April 21, 2026',
    published_at: '2026-03-10T00:00:00Z',
    duration_months: null
  },
  {
    slug: 'gates-foundation-micronutrient-absorption',
    title: 'Gates Foundation: Addressing Barriers to Micronutrient Absorption',
    funding_org: 'Bill & Melinda Gates Foundation',
    opportunity_id: 'GC-NUTRITION-2026',
    teaser: '$250,000 (18-month Phase 1) Grand Challenge solving biological constraints to nutrition — gut inflammation, dysbiosis, nutrient absorption barriers.',
    full_description: 'Solving biological constraints to nutrition (e.g., gut inflammation or dysbiosis) that prevent people from absorbing nutrients from fortified foods. Phase 1 with high potential for Phase 2 scaling funds ($1M+).',
    target_audience: 'Research-heavy startups and clinical teams',
    min_amount: 250000, max_amount: 250000, currency: 'USD',
    funding_rate: '100%', funding_type: 'Research Grant', co_financing_required: false,
    duration_months: 18,
    deadline: '2026-04-28T23:59:00+00:00', deadline_timezone: 'UTC',
    deadline_display_text: 'April 28, 2026',
    location: 'Global', sector: 'Health & WASH',
    implementation_area: 'Global', category: 'Deep Science',
    countries: ['Global'], regions: ['Global'],
    tags: ['nutrition', 'grand-challenge', 'research', 'biotech'],
    application_link: null,
    external_application_url: 'https://gcgh.grandchallenges.org',
    application_platform: 'Grand Challenges',
    eligibility_summary: 'Must address physiological barriers with scalable, cost-effective interventions.',
    eligibility_checklist: [{ item: 'Must address physiological barriers, not just food production' }, { item: 'Requires path to scalable, cost-effective interventions for low-resource settings' }],
    status: 'closed', priority: 'normal', is_featured: false, notify_me_enabled: true,
    archived_reason: 'Deadline passed April 28, 2026',
    published_at: '2026-03-05T00:00:00Z'
  },
  {
    slug: 'agency-fund-spring-2026',
    title: 'The Agency Fund: Spring 2026 Open Call (Stage 1)',
    funding_org: 'The Agency Fund',
    opportunity_id: 'TAF-S26',
    teaser: '$75,000–$500,000 for AI-enabled tools that help people navigate life-changing decisions in healthcare, education, or migration.',
    full_description: 'AI-enabled tools that help people navigate life-changing decisions (e.g., healthcare, education, or migration). Early-stage pilot to growth-stage scaling. Must have clear path to reaching 1 million+ users.',
    target_audience: 'AI for Social Good and behavioral-tech startups',
    min_amount: 75000, max_amount: 500000, currency: 'USD',
    funding_rate: '100%', funding_type: 'Grant', co_financing_required: false,
    deadline: '2026-04-26T23:59:00+00:00', deadline_timezone: 'UTC',
    deadline_display_text: 'April 26, 2026 (Stage 1 EOI)',
    location: 'Global', sector: 'AI & Data Science',
    implementation_area: 'Global', category: 'Human Agency',
    countries: ['Global'], regions: ['Global'],
    tags: ['AI', 'social-good', 'behavioral-tech', 'decision-tools'],
    application_link: null,
    external_application_url: 'https://www.theagencyfund.org',
    application_platform: 'Agency Fund',
    eligibility_summary: 'Must have 1,000+ users and scientific evidence of impact.',
    eligibility_checklist: [{ item: 'Should already be working with at least 1,000 users' }, { item: 'Must be grounded in scientific evidence of impact' }],
    status: 'closed', priority: 'normal', is_featured: false, notify_me_enabled: true,
    archived_reason: 'Deadline passed April 26, 2026',
    published_at: '2026-03-15T00:00:00Z',
    duration_months: null
  },
];

async function seed() {
  for (const grant of grants) {
    const { error } = await sb.from('grants').upsert(grant, { onConflict: 'slug' });
    if (error) {
      console.error(error.message);
    }
  }
}

seed().catch(console.error);
